version: '3.5'

services:
  api1:
    image: charliecharlie/rinhabackend
    hostname: api1
    depends_on:
      - postgres
    environment:
      SECRET_KEY_BASE: uodN/bT/69cDyfLm+qwKUWKg88yyMrffUEmhedFblqDOOBxsbsJfPKFmqZKM+VOg
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rinhabackend_prod
    expose:
      - "4000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.75GB'

  api2:
    image: charliecharlie/rinhabackend
    hostname: api2
    depends_on:
      - postgres
    environment:
      SECRET_KEY_BASE: uodN/bT/69cDyfLm+qwKUWKg88yyMrffUEmhedFblqDOOBxsbsJfPKFmqZKM+VOg
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rinhabackend_prod
    expose:
      - "4000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.75GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  postgres:
    container_name: "postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhabackend_prod
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.25GB'

networks:
  default:
    name: rinhabackend
